const actionTypes = {
    GET_AUTH_TOKEN: "GET_AUTH_TOKEN",
    USER_LOGOUT:'USER_LOGOUT',
    GET_AUTH_TOKEN_SUCCESS : 'GET_AUTH_TOKEN_SUCCESS',
    GET_AUTH_TOKEN_FAILURE : 'GET_AUTH_TOKEN_FAILURE'
}

export default actionTypes;